"""
Create PERFECT HRMS schema based on actual HRMS backend models.
This script was generated by reading all models from the HRMS repository.
"""
from sqlalchemy import create_engine, text
from app.config import settings
import logging

logger = logging.getLogger(__name__)


def create_perfect_tenant_schema(db_name: str, tenant_id: int) -> dict:
    """
    Drop all tables and recreate them with the EXACT structure from HRMS models.
    
    This ensures 100% compatibility with the HRMS backend.
    
    Args:
        db_name: Name of the tenant database
        tenant_id: The Super Admin tenant ID
        
    Returns:
        dict with status and message
    """
    try:
        # Construct database URL
        db_url = f"{settings.POSTGRES_SERVER_URL.rsplit('/', 1)[0]}/{db_name}"
        db_url = db_url.replace('/postgres', f'/{db_name}')
        
        engine = create_engine(db_url, pool_pre_ping=True)
        
        with engine.connect() as connection:
            # Drop all existing tables (CASCADE to handle foreign keys)
            logger.info(f"Dropping all tables in {db_name}...")
            connection.execute(text("""
                DROP SCHEMA public CASCADE;
                CREATE SCHEMA public;
                GRANT ALL ON SCHEMA public TO public;
            """))
            
            logger.info(f"Creating perfect schema in {db_name}...")
            
            # Create all tables in correct order (respecting foreign key dependencies)
            connection.execute(text("""
                -- ========================================
                -- CORE TABLES
                -- ========================================
                
                CREATE TABLE departments (
                    id SERIAL PRIMARY KEY,
                    name VARCHAR NOT NULL UNIQUE,
                    description TEXT,
                    manager_id INTEGER,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                
                CREATE TABLE users (
                    id SERIAL PRIMARY KEY,
                    tenant_id INTEGER NOT NULL DEFAULT 1,
                    email VARCHAR UNIQUE,
                    full_name VARCHAR NOT NULL UNIQUE,
                    hashed_password VARCHAR NOT NULL,
                    role VARCHAR NOT NULL DEFAULT 'employee',
                    is_admin BOOLEAN NOT NULL DEFAULT false,
                    is_active BOOLEAN NOT NULL DEFAULT true,
                    job_role VARCHAR,
                    department_id INTEGER REFERENCES departments(id) ON DELETE SET NULL,
                    manager_id INTEGER,
                    avatar_url VARCHAR,
                    phone VARCHAR,
                    hire_date TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    timezone VARCHAR NOT NULL DEFAULT 'UTC',
                    locale VARCHAR NOT NULL DEFAULT 'en',
                    theme VARCHAR NOT NULL DEFAULT 'light',
                    email_notifications BOOLEAN NOT NULL DEFAULT true,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_users_id ON users(id);
                CREATE INDEX ix_users_email ON users(email);
                CREATE INDEX ix_users_tenant_id ON users(tenant_id);
                
                -- Add foreign keys that reference users
                ALTER TABLE departments ADD CONSTRAINT fk_departments_manager 
                    FOREIGN KEY (manager_id) REFERENCES users(id) ON DELETE SET NULL;
                ALTER TABLE users ADD CONSTRAINT fk_users_manager 
                    FOREIGN KEY (manager_id) REFERENCES users(id) ON DELETE SET NULL;
                
                -- ========================================
                -- SESSION MANAGEMENT
                -- ========================================
                
                CREATE TABLE user_sessions (
                    id SERIAL PRIMARY KEY,
                    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    token_hash VARCHAR NOT NULL,
                    device_info VARCHAR,
                    ip_address VARCHAR,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    last_seen TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    is_active INTEGER NOT NULL DEFAULT 1
                );
                CREATE INDEX ix_user_sessions_id ON user_sessions(id);
                CREATE INDEX ix_user_sessions_user_id ON user_sessions(user_id);
                CREATE INDEX ix_user_sessions_token_hash ON user_sessions(token_hash);
                
                -- ========================================
                -- ROLES & PERMISSIONS
                -- ========================================
                
                CREATE TABLE roles (
                    id SERIAL PRIMARY KEY,
                    name VARCHAR(50) NOT NULL UNIQUE,
                    description TEXT,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_roles_id ON roles(id);
                
                CREATE TABLE permissions (
                    id SERIAL PRIMARY KEY,
                    resource VARCHAR(50) NOT NULL,
                    action VARCHAR(50) NOT NULL,
                    description TEXT,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_permissions_id ON permissions(id);
                
                CREATE TABLE user_roles (
                    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
                    PRIMARY KEY (user_id, role_id)
                );
                
                CREATE TABLE role_permissions (
                    role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
                    permission_id INTEGER NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
                    PRIMARY KEY (role_id, permission_id)
                );
                
                CREATE TABLE custom_roles (
                    id SERIAL PRIMARY KEY,
                    name VARCHAR(50) NOT NULL UNIQUE,
                    display_name VARCHAR(100) NOT NULL,
                    description TEXT,
                    is_system_role BOOLEAN NOT NULL DEFAULT false,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_custom_roles_id ON custom_roles(id);
                CREATE INDEX ix_custom_roles_name ON custom_roles(name);
                
                CREATE TABLE role_permissions_v2 (
                    id SERIAL PRIMARY KEY,
                    role VARCHAR(50) NOT NULL,
                    resource VARCHAR(50) NOT NULL,
                    can_view BOOLEAN NOT NULL DEFAULT false,
                    can_create BOOLEAN NOT NULL DEFAULT false,
                    can_edit BOOLEAN NOT NULL DEFAULT false,
                    can_delete BOOLEAN NOT NULL DEFAULT false,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_role_permissions_v2_id ON role_permissions_v2(id);
                
                -- ========================================
                -- PROJECTS & TASKS
                -- ========================================
                
                CREATE TABLE projects (
                    id SERIAL PRIMARY KEY,
                    title VARCHAR(255) NOT NULL,
                    description TEXT,
                    created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE SET NULL,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_projects_id ON projects(id);
                CREATE INDEX ix_projects_created_by ON projects(created_by);
                
                CREATE TABLE tasks (
                    id SERIAL PRIMARY KEY,
                    title VARCHAR NOT NULL,
                    description TEXT,
                    status VARCHAR NOT NULL DEFAULT 'To-Do',
                    priority VARCHAR NOT NULL DEFAULT 'Medium',
                    assignee_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    assignee VARCHAR,
                    created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE SET NULL,
                    project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE,
                    position INTEGER NOT NULL DEFAULT 1,
                    due_date VARCHAR,
                    completed_at TIMESTAMP WITH TIME ZONE,
                    is_private BOOLEAN NOT NULL DEFAULT false,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_tasks_id ON tasks(id);
                CREATE INDEX ix_tasks_assignee_id ON tasks(assignee_id);
                CREATE INDEX ix_tasks_created_by ON tasks(created_by);
                CREATE INDEX ix_tasks_project_id ON tasks(project_id);
                
                CREATE TABLE comments (
                    id SERIAL PRIMARY KEY,
                    content TEXT NOT NULL,
                    task_id INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
                    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    parent_comment_id INTEGER REFERENCES comments(id) ON DELETE CASCADE,
                    is_edited BOOLEAN DEFAULT false,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_comments_id ON comments(id);
                
                -- ========================================
                -- COMMUNICATION
                -- ========================================
                
                CREATE TABLE chats (
                    id SERIAL PRIMARY KEY,
                    name VARCHAR(255),
                    type VARCHAR(50) NOT NULL,
                    department_id INTEGER REFERENCES departments(id) ON DELETE SET NULL,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_chats_id ON chats(id);
                
                CREATE TABLE messages (
                    id SERIAL PRIMARY KEY,
                    sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    chat_id INTEGER NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
                    text TEXT NOT NULL,
                    timestamp TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    is_edited INTEGER NOT NULL DEFAULT 0,
                    edited_at TIMESTAMP WITH TIME ZONE
                );
                CREATE INDEX ix_messages_id ON messages(id);
                CREATE INDEX ix_messages_sender_id ON messages(sender_id);
                CREATE INDEX ix_messages_chat_id ON messages(chat_id);
                CREATE INDEX ix_messages_timestamp ON messages(timestamp);
                
                CREATE TABLE chat_participants (
                    chat_id INTEGER NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
                    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    joined_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
                    PRIMARY KEY (chat_id, user_id)
                );
                
                -- ========================================
                -- TIME TRACKING
                -- ========================================
                
                CREATE TABLE time_entries (
                    id SERIAL PRIMARY KEY,
                    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    clock_in TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    clock_out TIMESTAMP WITH TIME ZONE,
                    break_start TIMESTAMP WITH TIME ZONE,
                    break_end TIMESTAMP WITH TIME ZONE,
                    is_terrain BOOLEAN NOT NULL DEFAULT false,
                    work_summary TEXT,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_time_entries_id ON time_entries(id);
                CREATE INDEX ix_time_entries_user_id ON time_entries(user_id);
                
                -- ========================================
                -- LEAVE MANAGEMENT
                -- ========================================
                
                CREATE TABLE leave_types (
                    id SERIAL PRIMARY KEY,
                    name VARCHAR(50) NOT NULL UNIQUE,
                    description TEXT,
                    default_days_per_year INTEGER NOT NULL DEFAULT 0,
                    requires_approval BOOLEAN NOT NULL DEFAULT true,
                    is_active BOOLEAN NOT NULL DEFAULT true,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_leave_types_id ON leave_types(id);
                
                CREATE TABLE leave_balances (
                    id SERIAL PRIMARY KEY,
                    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    leave_type_id INTEGER NOT NULL REFERENCES leave_types(id) ON DELETE CASCADE,
                    total_days NUMERIC(5,2) NOT NULL DEFAULT 0,
                    used_days NUMERIC(5,2) NOT NULL DEFAULT 0,
                    remaining_days NUMERIC(5,2) NOT NULL DEFAULT 0,
                    year INTEGER NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_leave_balances_id ON leave_balances(id);
                
                CREATE TABLE leave_requests (
                    id SERIAL PRIMARY KEY,
                    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    leave_type_id INTEGER NOT NULL REFERENCES leave_types(id) ON DELETE CASCADE,
                    start_date DATE NOT NULL,
                    end_date DATE NOT NULL,
                    total_days NUMERIC(5,2) NOT NULL,
                    reason TEXT,
                    status VARCHAR(20) NOT NULL DEFAULT 'pending',
                    reviewed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    reviewed_at TIMESTAMP WITH TIME ZONE,
                    review_comments TEXT,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_leave_requests_id ON leave_requests(id);
                
                -- ========================================
                -- PERFORMANCE MANAGEMENT
                -- ========================================
                
                CREATE TABLE performance_objectives (
                    id SERIAL PRIMARY KEY,
                    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    title VARCHAR(255) NOT NULL,
                    description TEXT,
                    status VARCHAR NOT NULL DEFAULT 'ACTIVE',
                    start_date TIMESTAMP WITH TIME ZONE,
                    due_date TIMESTAMP WITH TIME ZONE,
                    progress FLOAT NOT NULL DEFAULT 0.0,
                    created_by_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    approved_by_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    approval_status VARCHAR NOT NULL DEFAULT 'PENDING',
                    approval_date TIMESTAMP WITH TIME ZONE,
                    rejection_reason TEXT,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_performance_objectives_id ON performance_objectives(id);
                CREATE INDEX ix_performance_objectives_user_id ON performance_objectives(user_id);
                CREATE INDEX ix_performance_objectives_created_by_id ON performance_objectives(created_by_id);
                CREATE INDEX ix_performance_objectives_approved_by_id ON performance_objectives(approved_by_id);
                
                CREATE TABLE performance_key_results (
                    id SERIAL PRIMARY KEY,
                    objective_id INTEGER NOT NULL REFERENCES performance_objectives(id) ON DELETE CASCADE,
                    title VARCHAR(255) NOT NULL,
                    target_value FLOAT,
                    current_value FLOAT NOT NULL DEFAULT 0.0,
                    unit VARCHAR(50),
                    weight FLOAT NOT NULL DEFAULT 1.0,
                    status VARCHAR NOT NULL DEFAULT 'OPEN',
                    progress FLOAT NOT NULL DEFAULT 0.0,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_performance_key_results_id ON performance_key_results(id);
                CREATE INDEX ix_performance_key_results_objective_id ON performance_key_results(objective_id);
                
                CREATE TABLE review_cycles (
                    id SERIAL PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    start_date TIMESTAMP WITH TIME ZONE NOT NULL,
                    end_date TIMESTAMP WITH TIME ZONE NOT NULL,
                    status VARCHAR NOT NULL DEFAULT 'DRAFT',
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_review_cycles_id ON review_cycles(id);
                
                CREATE TABLE review_questions (
                    id SERIAL PRIMARY KEY,
                    cycle_id INTEGER NOT NULL REFERENCES review_cycles(id) ON DELETE CASCADE,
                    section VARCHAR NOT NULL,
                    prompt TEXT NOT NULL,
                    scale_min INTEGER NOT NULL DEFAULT 1,
                    scale_max INTEGER NOT NULL DEFAULT 5
                );
                CREATE INDEX ix_review_questions_id ON review_questions(id);
                CREATE INDEX ix_review_questions_cycle_id ON review_questions(cycle_id);
                
                CREATE TABLE review_responses (
                    id SERIAL PRIMARY KEY,
                    cycle_id INTEGER NOT NULL REFERENCES review_cycles(id) ON DELETE CASCADE,
                    reviewee_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    reviewer_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    reviewer_type VARCHAR NOT NULL,
                    question_id INTEGER NOT NULL REFERENCES review_questions(id) ON DELETE CASCADE,
                    rating INTEGER,
                    comment TEXT,
                    is_anonymous_peer BOOLEAN NOT NULL DEFAULT false,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_review_responses_id ON review_responses(id);
                CREATE INDEX ix_review_responses_cycle_id ON review_responses(cycle_id);
                CREATE INDEX ix_review_responses_reviewee_id ON review_responses(reviewee_id);
                CREATE INDEX ix_review_responses_reviewer_id ON review_responses(reviewer_id);
                CREATE INDEX ix_review_responses_question_id ON review_responses(question_id);
                
                CREATE TABLE competencies (
                    id SERIAL PRIMARY KEY,
                    name VARCHAR(255) NOT NULL UNIQUE,
                    description TEXT
                );
                CREATE INDEX ix_competencies_id ON competencies(id);
                
                CREATE TABLE competency_scores (
                    id SERIAL PRIMARY KEY,
                    cycle_id INTEGER NOT NULL REFERENCES review_cycles(id) ON DELETE CASCADE,
                    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    competency_id INTEGER NOT NULL REFERENCES competencies(id) ON DELETE CASCADE,
                    source VARCHAR NOT NULL,
                    score FLOAT NOT NULL
                );
                CREATE INDEX ix_competency_scores_id ON competency_scores(id);
                
                -- ========================================
                -- FEEDBACK SYSTEM
                -- ========================================
                
                CREATE TABLE feedback (
                    id SERIAL PRIMARY KEY,
                    author_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    recipient_type VARCHAR(8) NOT NULL,
                    recipient_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    content TEXT NOT NULL,
                    is_anonymous BOOLEAN NOT NULL DEFAULT false,
                    sentiment_label VARCHAR(8),
                    sentiment_score INTEGER,
                    keywords TEXT,
                    parent_id INTEGER REFERENCES feedback(id) ON DELETE CASCADE,
                    is_flagged BOOLEAN NOT NULL DEFAULT false,
                    flagged_reason VARCHAR,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_feedback_id ON feedback(id);
                
                CREATE TABLE feedback_keywords (
                    id SERIAL PRIMARY KEY,
                    keyword VARCHAR NOT NULL,
                    frequency INTEGER NOT NULL DEFAULT 1,
                    sentiment_context VARCHAR,
                    department VARCHAR,
                    first_seen DATE NOT NULL,
                    last_seen DATE NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_feedback_keywords_id ON feedback_keywords(id);
                CREATE INDEX ix_feedback_keywords_keyword ON feedback_keywords(keyword);
                CREATE INDEX ix_feedback_keywords_frequency ON feedback_keywords(frequency);
                CREATE INDEX ix_feedback_keywords_department ON feedback_keywords(department);
                
                CREATE TABLE daily_feedback_aggregates (
                    id SERIAL PRIMARY KEY,
                    date DATE NOT NULL UNIQUE,
                    feedback_count INTEGER NOT NULL DEFAULT 0,
                    sentiment_avg FLOAT NOT NULL DEFAULT 0.0,
                    sentiment_positive_count INTEGER NOT NULL DEFAULT 0,
                    sentiment_neutral_count INTEGER NOT NULL DEFAULT 0,
                    sentiment_negative_count INTEGER NOT NULL DEFAULT 0,
                    anonymous_count INTEGER NOT NULL DEFAULT 0,
                    flagged_count INTEGER NOT NULL DEFAULT 0,
                    department_breakdown TEXT,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_daily_feedback_aggregates_id ON daily_feedback_aggregates(id);
                
                -- ========================================
                -- NOTIFICATIONS
                -- ========================================
                
                CREATE TABLE notifications (
                    id SERIAL PRIMARY KEY,
                    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    type VARCHAR(50) NOT NULL,
                    title VARCHAR(255) NOT NULL,
                    message TEXT NOT NULL,
                    data JSON,
                    is_read BOOLEAN NOT NULL DEFAULT false,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    read_at TIMESTAMP WITH TIME ZONE
                );
                CREATE INDEX ix_notifications_id ON notifications(id);
                CREATE INDEX ix_notifications_user_id ON notifications(user_id);
                CREATE INDEX ix_notifications_type ON notifications(type);
                CREATE INDEX ix_notifications_is_read ON notifications(is_read);
                CREATE INDEX ix_notifications_created_at ON notifications(created_at);
                
                CREATE TABLE push_notification_tokens (
                    id SERIAL PRIMARY KEY,
                    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    token VARCHAR(500) NOT NULL,
                    platform VARCHAR(20) NOT NULL,
                    device_info JSON,
                    is_active BOOLEAN NOT NULL DEFAULT true,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_push_notification_tokens_id ON push_notification_tokens(id);
                CREATE INDEX ix_push_notification_tokens_user_id ON push_notification_tokens(user_id);
                CREATE INDEX ix_push_notification_tokens_platform ON push_notification_tokens(platform);
                CREATE INDEX ix_push_notification_tokens_is_active ON push_notification_tokens(is_active);
            """))
            
            # Create user_notification_preferences table separately (too many columns)
            connection.execute(text("""
                CREATE TABLE user_notification_preferences (
                    id SERIAL PRIMARY KEY,
                    user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
                    email_task_assigned BOOLEAN DEFAULT true,
                    email_task_completed BOOLEAN DEFAULT true,
                    email_task_overdue BOOLEAN DEFAULT true,
                    inapp_task_assigned BOOLEAN DEFAULT true,
                    inapp_task_completed BOOLEAN DEFAULT true,
                    inapp_task_overdue BOOLEAN DEFAULT true,
                    push_task_assigned BOOLEAN DEFAULT true,
                    push_task_completed BOOLEAN DEFAULT true,
                    push_task_overdue BOOLEAN DEFAULT true,
                    email_project_assigned BOOLEAN DEFAULT true,
                    inapp_project_assigned BOOLEAN DEFAULT true,
                    push_project_assigned BOOLEAN DEFAULT true,
                    email_late_to_work BOOLEAN DEFAULT true,
                    inapp_late_to_work BOOLEAN DEFAULT true,
                    push_late_to_work BOOLEAN DEFAULT true,
                    email_comment_reply BOOLEAN DEFAULT true,
                    inapp_comment_reply BOOLEAN DEFAULT true,
                    push_comment_reply BOOLEAN DEFAULT true,
                    email_task_reviewed BOOLEAN DEFAULT true,
                    inapp_task_reviewed BOOLEAN DEFAULT true,
                    push_task_reviewed BOOLEAN DEFAULT true,
                    email_feedback_received BOOLEAN DEFAULT true,
                    email_public_feedback BOOLEAN DEFAULT true,
                    email_feedback_replied BOOLEAN DEFAULT true,
                    inapp_feedback_received BOOLEAN DEFAULT true,
                    inapp_public_feedback BOOLEAN DEFAULT true,
                    inapp_feedback_replied BOOLEAN DEFAULT true,
                    push_feedback_received BOOLEAN DEFAULT true,
                    push_public_feedback BOOLEAN DEFAULT true,
                    push_feedback_replied BOOLEAN DEFAULT true,
                    email_peer_review BOOLEAN DEFAULT true,
                    email_manager_review BOOLEAN DEFAULT true,
                    email_review_due BOOLEAN DEFAULT true,
                    inapp_peer_review BOOLEAN DEFAULT true,
                    inapp_manager_review BOOLEAN DEFAULT true,
                    inapp_review_due BOOLEAN DEFAULT true,
                    push_peer_review BOOLEAN DEFAULT true,
                    push_manager_review BOOLEAN DEFAULT true,
                    push_review_due BOOLEAN DEFAULT true,
                    email_goal_approved BOOLEAN DEFAULT true,
                    email_goal_rejected BOOLEAN DEFAULT true,
                    inapp_goal_approved BOOLEAN DEFAULT true,
                    inapp_goal_rejected BOOLEAN DEFAULT true,
                    push_goal_approved BOOLEAN DEFAULT true,
                    push_goal_rejected BOOLEAN DEFAULT true,
                    email_leave_approved BOOLEAN DEFAULT true,
                    email_leave_rejected BOOLEAN DEFAULT true,
                    inapp_leave_approved BOOLEAN DEFAULT true,
                    inapp_leave_rejected BOOLEAN DEFAULT true,
                    push_leave_approved BOOLEAN DEFAULT true,
                    push_leave_rejected BOOLEAN DEFAULT true,
                    email_private_message BOOLEAN DEFAULT true,
                    email_department_message BOOLEAN DEFAULT true,
                    email_company_message BOOLEAN DEFAULT true,
                    inapp_private_message BOOLEAN DEFAULT true,
                    inapp_department_message BOOLEAN DEFAULT true,
                    inapp_company_message BOOLEAN DEFAULT true,
                    push_private_message BOOLEAN DEFAULT true,
                    push_department_message BOOLEAN DEFAULT true,
                    push_company_message BOOLEAN DEFAULT true,
                    email_mention BOOLEAN DEFAULT true,
                    inapp_mention BOOLEAN DEFAULT true,
                    push_mention BOOLEAN DEFAULT true,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_user_notification_preferences_id ON user_notification_preferences(id);
                CREATE INDEX ix_user_notification_preferences_user_id ON user_notification_preferences(user_id);
            """))
            
            # Office & Meeting Booking + KPI Snapshots + Organization Settings
            connection.execute(text("""
                -- ========================================
                -- OFFICE & MEETING BOOKING
                -- ========================================
                
                CREATE TABLE offices (
                    id SERIAL PRIMARY KEY,
                    name VARCHAR(100) NOT NULL UNIQUE,
                    location VARCHAR(200),
                    floor VARCHAR(50),
                    capacity INTEGER NOT NULL DEFAULT 1,
                    description TEXT,
                    amenities JSON,
                    photo_url VARCHAR(500),
                    is_active BOOLEAN NOT NULL DEFAULT true,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_offices_id ON offices(id);
                
                CREATE TABLE meeting_bookings (
                    id SERIAL PRIMARY KEY,
                    office_id INTEGER NOT NULL REFERENCES offices(id) ON DELETE CASCADE,
                    title VARCHAR(200) NOT NULL,
                    description TEXT,
                    organizer_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
                    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
                    participant_ids JSON,
                    status VARCHAR(20) NOT NULL DEFAULT 'upcoming',
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
                CREATE INDEX ix_meeting_bookings_id ON meeting_bookings(id);
                CREATE INDEX ix_meeting_bookings_start_time ON meeting_bookings(start_time);
                CREATE INDEX ix_meeting_bookings_end_time ON meeting_bookings(end_time);
                
                -- ========================================
                -- ANALYTICS
                -- ========================================
                
                CREATE TABLE kpi_snapshots (
                    id SERIAL PRIMARY KEY,
                    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    kpi_name VARCHAR(255) NOT NULL,
                    value FLOAT NOT NULL,
                    unit VARCHAR(50),
                    snapshot_date TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    notes TEXT,
                    period VARCHAR(20) NOT NULL DEFAULT 'monthly',
                    visibility VARCHAR(20) NOT NULL DEFAULT 'manager',
                    measured_by_id INTEGER REFERENCES users(id) ON DELETE SET NULL
                );
                CREATE INDEX ix_kpi_snapshots_id ON kpi_snapshots(id);
                CREATE INDEX ix_kpi_snapshots_user_id ON kpi_snapshots(user_id);
                CREATE INDEX ix_kpi_snapshots_kpi_name ON kpi_snapshots(kpi_name);
                CREATE INDEX ix_kpi_snapshots_snapshot_date ON kpi_snapshots(snapshot_date);
                
                -- ========================================
                -- ORGANIZATION SETTINGS
                -- ========================================
                
                CREATE TABLE organization_settings (
                    id SERIAL PRIMARY KEY,
                    allow_breaks BOOLEAN NOT NULL DEFAULT true,
                    require_documentation BOOLEAN NOT NULL DEFAULT false,
                    orgchart_show_unassigned_panel BOOLEAN NOT NULL DEFAULT true,
                    orgchart_manager_subtree_edit BOOLEAN NOT NULL DEFAULT true,
                    orgchart_department_colors BOOLEAN NOT NULL DEFAULT true,
                    orgchart_compact_view BOOLEAN NOT NULL DEFAULT false,
                    orgchart_show_connectors BOOLEAN NOT NULL DEFAULT true,
                    feedback_allow_anonymous BOOLEAN NOT NULL DEFAULT true,
                    feedback_enable_threading BOOLEAN NOT NULL DEFAULT true,
                    feedback_enable_moderation BOOLEAN NOT NULL DEFAULT true,
                    feedback_notify_managers BOOLEAN NOT NULL DEFAULT true,
                    feedback_weekly_digest BOOLEAN NOT NULL DEFAULT true,
                    performance_module_enabled BOOLEAN NOT NULL DEFAULT true,
                    performance_allow_self_goals BOOLEAN NOT NULL DEFAULT true,
                    performance_require_goal_approval BOOLEAN NOT NULL DEFAULT true,
                    performance_enable_peer_reviews BOOLEAN NOT NULL DEFAULT true,
                    performance_allow_anonymous_peer BOOLEAN NOT NULL DEFAULT true,
                    performance_show_kpi_trends BOOLEAN NOT NULL DEFAULT true,
                    performance_top_performer_threshold INTEGER NOT NULL DEFAULT 85,
                    performance_monthly_reports BOOLEAN NOT NULL DEFAULT true,
                    email_notifications_enabled BOOLEAN NOT NULL DEFAULT true,
                    inapp_notifications_enabled BOOLEAN NOT NULL DEFAULT true,
                    daily_summary_enabled BOOLEAN NOT NULL DEFAULT true,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
                );
            """))
            
            # Update admin users with correct tenant_id
            result = connection.execute(
                text("""
                    UPDATE users 
                    SET tenant_id = :tenant_id,
                        is_admin = true
                    WHERE role = 'admin';
                """),
                {"tenant_id": tenant_id}
            )
            updated_count = result.rowcount
            
            connection.commit()
            
            logger.info(f"✅ Perfect schema created for {db_name}, updated {updated_count} admin users")
            
            return {
                "status": "success",
                "message": f"Perfect schema created for {db_name}, updated {updated_count} admin users"
            }
            
    except Exception as e:
        logger.error(f"Failed to create perfect schema for {db_name}: {str(e)}")
        return {
            "status": "error",
            "message": f"Failed to create perfect schema: {str(e)}"
        }


